common: &common
  adapter: postgresql
  encoding: unicode
  username: <%= Figaro.env.DBUSER %>
  password: <%= Figaro.env.DBPASS %>
  
development:
  <<: *common
  database: recuriting_app_developement
  #database: groundfloor_restore
  port: 5432
  host: localhost

test:
  <<: *common
  database: recuriting_app_test
  port: 5432
  host: localhost

production:
  <<: *common
  database: recuriting_app_production
  port: 5432
  host: localhost
