common: &common
  adapter: postgresql
  encoding: unicode
  # username: add one if needed
  # password: add one if needed
  
development:
  <<: *common
  database: recruiting_app_development
  #database: groundfloor_restore
  port: 5432
  host: localhost

test:
  <<: *common
  database: recruiting_app_test
  port: 5432
  host: localhost

production:
  <<: *common
  database: recruiting_app_production
  port: 5432
  host: localhost
